packaging_format = 2

id = "simplemachines"
name = "Simple Machines Forum"
description.en = "Forum example"

version = "3.0~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0-only"

[integration]
yunohost = ">= 11.2.4"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/site"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.custom_error_file]
    ask.en = "Activate the custom error file use"
    ask.fr = "Activer l'utilisation du fichier d'erreur personnalis√©"
    type = "boolean"
    default = false
    help = "Once custom error enabled, you can add/create a custom `404.html` file in a directory `www/error`."

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/SimpleMachines/SMF/archive/refs/tags/v2.1.6.tar.gz"
        sha256 = "329037e8d3a04721732f2df2fe4eb12e6300c0aef2e0639e92bac56856120d11"
        autoupdate.upstream = "https://github.com/SimpleMachines/SMF"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "nginx postgresql postgresql-contrib php8.4-pgsql"  # Kind of "dummy" value to be sure to have a non-empty dep list

    [resources.composer]
    version = "2.9.3"
