packaging_format = 2

id = "simplemachines"
name = "Simple Machines Forum"
description.en = "Forum example"

version = "3.0~ynh1"

maintainers = []

[upstream]
license = "GPL-3.0-only"

[integration]
yunohost = ">= 11.2.4"
architectures = "all"
multi_instance = true
ldap = "not_relevant"
sso = "not_relevant"
disk = "50M"
ram.build = "50M"
ram.runtime = "50M"

[install]
    [install.domain]
    type = "domain"

    [install.path]
    type = "path"
    default = "/site"

    [install.init_main_permission]
    type = "group"
    default = "visitors"

    [install.phpversion]
    ask.en = "Choose a PHP version you want to use for your app"
    ask.fr = "Choisissez une version PHP que vous souhaitez utiliser pour votre application"
    type = "select"
    choices = ["none", "7.4", "8.0", "8.1", "8.2", "8.3", "8.4"]
    default = "8.4"

    [install.database]
    ask.en = "Do you need a database?"
    ask.fr = "Avez-vous besoin d'une base de données ?"
    type = "select"
    choices = [ "none", "mysql", "postgresql" ]
    default = "postgres"

    [install.custom_error_file]
    ask.en = "Activate the custom error file use"
    ask.fr = "Activer l'utilisation du fichier d'erreur personnalisé"
    type = "boolean"
    default = false
    help = "Once custom error enabled, you can add/create a custom `404.html` file in a directory `www/error`."

[resources]

    [resources.sources]

        [resources.sources.main]
        url = "https://github.com/SimpleMachines/SMF/archive/refs/tags/v2.1.6.tar.gz"
        autoupdate.upstream = "https://github.com/SimpleMachines/SMF"
        autoupdate.strategy = "latest_github_tag"

    [resources.system_user]

    [resources.install_dir]
    group = "www-data:r-x"

    [resources.permissions]
    main.url = "/"

    [resources.apt]
    packages = "nginx"  # Kind of "dummy" value to be sure to have a non-empty dep list
    packages_from_raw_bash = """
        if [[ "$database" == "mysql" ]]; then
            echo "mariadb-server"

            if [[ "$phpversion" != none ]]; then
                echo "php${phpversion}-mysql"
            fi
        elif [[ "$database" == "postgresql" ]]; then
            echo "postgresql postgresql-contrib"

            if [[ "$phpversion" != none ]]; then
                echo "php${phpversion}-pgsql"
            fi
        fi

        if [[ "$phpversion" != none ]]; then
            echo "php${phpversion}-fpm"
        fi
    """

    [resources.composer]
    version = "2.9.3"
